// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZF5j329MUp3k8Qiw44KVt8adHpP8iTCQ',
    appId: '1:649831928117:web:6c04bd000c48f985b17c7c',
    messagingSenderId: '649831928117',
    projectId: 'store-f4fdf',
    authDomain: 'store-f4fdf.firebaseapp.com',
    storageBucket: 'store-f4fdf.appspot.com',
    measurementId: 'G-KZVQYHYFQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3p_m2JIpmtV18ZNV5NJ3SEgCOxnsvlmA',
    appId: '1:649831928117:android:5424123494e1d76bb17c7c',
    messagingSenderId: '649831928117',
    projectId: 'store-f4fdf',
    storageBucket: 'store-f4fdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWb597cElt64__L2DSB0RcJPuDNSpTNJc',
    appId: '1:649831928117:ios:8018e39b61c4ffa8b17c7c',
    messagingSenderId: '649831928117',
    projectId: 'store-f4fdf',
    storageBucket: 'store-f4fdf.appspot.com',
    iosClientId: '649831928117-cq38pq2v336egt1chooirgh371suo27d.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );
}
